### PR TITLE
Search - Recent Searches

### PR DESCRIPTION
**Pull request by rupin90**
###  Video reference
https://www.awesomescreenshot.com/video/11319930?key=1906ddc480c5bbe6c3017ab4ca251fc8

###  - Here is how local storage currently looks like, keeping it simple on how we save key/values, can be updated if needed for search recent history
Screen Shot 2022-09-26 at 7 31 50 AM

 ### Tasks ------------------------
- [x] Adding packages (trial) - Downshift and recent searches , trial ended and only Downshift was needed. Cleared up
- [x] Local storage - Define key/value object
- [x] CSS - Dropdown outline and buttons alignment
- [x] searching on a new item should set item in local storage
- [x] on Focus of Search Input field - Open the dropdown (Menu Props) one letter to be entered at least
- [x] on Blur - Close the dropdown
- [x] Define opening Menu Props (recent search dropdown object)
- [x] Populate Initial items in the Menu Props from Local Storage
- [x] figure out highlighted index
- [x]  Menu Props Display - Focus on CSS - REMAINING - Adding Icons and some polishing 
- [x] clicking on X should remove item from recent search (basically remove item from local storage)
- [x] test edge scenarios with Downshift (recent search update items)
- [x] ClearSelection Method from Downshift NOT WORKING YET when trying to clear the  Search input field - This is working now

### CODE REVIEW

**Comment by jacksonh** [comment]
I know still in progress, but something a little weird happening with the search filter button on this version for me:

Screen Shot 2022-09-05 at 12 07 06

**Comment by rupin90** [comment]
> I know still in progress, but something a little weird happening with the search filter button on this version for me:
> 
> Screen Shot 2022-09-05 at 12 07 06

Yeah Because I haven't added the CSS yet, there is a button hiding behind the Menu bar as well so the CSS is broken for now, I tried  to fix but then it is not behaving as expected, :(. Sometimes adding functionality is so much easier than adding look and feel 😅 .

So right now focusing on adding some basic functionality and then will focus on the CSS.

**Comment by rupin90** [comment]
@jacksonh  - This is still in progress, some stuff is just doesn't want to work lol, however it is ready enough for the initial feedback that I can work on parallel as I complete the items remaining (see description)

**Comment by rupin90** [comment]
@jacksonh  - this PR is ready to be reviewed! Thank you for reviewing! 

What would be the next priority to work on?

**Comment by jacksonh** [comment]
Checking this out now. Sorry, missed that it was ready.

**Comment by jacksonh** [comment]
Thanks for the video, checking this out again to see.

**Comment by jacksonh** [comment]
Hey just one small (i hope) change. Could we make it display the recent searches on focus? So you don't even have to start typing to see one? 

I checked in Gmail and this is how they do it.

**Comment by rupin90** [comment]
> Hey just one small (i hope) change. Could we make it display the recent searches on focus? So you don't even have to start typing to see one?
> 
> I checked in Gmail and this is how they do it.

is this how you want it? - https://www.awesomescreenshot.com/video/11321109?key=91cf616acabcd0a910f41524347f7abc
I thought it is like how we have right now? 🤔

**Comment by jacksonh** [comment]
Huh, its a little different for me. It is delayed but thats probably because its loading, GitHub PRs isn't recent searches but similar UI https://www.loom.com/share/cc697951bc5c442599bf385a6ff2ac8e

**Comment by jacksonh** [comment]
Hey @rupin90 i think we can rebase and merge this one. Sorry it took so long

**Comment by jacksonh** [comment]
Hey @rupin90 i think we can rebase and merge this one. Sorry it took so long

**Comment by rupin90** [comment]
> Hey @rupin90 i think we can rebase and merge this one. Sorry it took so long

Thank you yay!!!!

I can pick up the next priority!!

**Comment by rupin90** [comment]
@jacksonh  - Can you please approve it! Thank you 🙏🏽 .

I can also pick up the next priority task, thank you!

**Review by jacksonh — APPROVED** [review]

**Pull request merged**
