### PR TITLE
Wrapping up the remaining task for integration feature

### PR DESCRIPTION
**Pull request by rupin90**
- [x]  Add title, currently only placeholder is there ???? . @jacksonh 
- [x] IS IT SAFE to  delete the other webhooks file which is under **settings**.  ????? @jacksonh 
- [x] New webHooks file is created under templates/integrations/Webhooks.

### CODE REVIEW

**Comment by jacksonh** [comment]
Hey @rupin90 how hard would it be on mobile to have the icon above the description? Now that the descriptions are a little longer it doesn't fit very well in mobile.

I'll also remove the padding on mobile.

Screen Shot 2022-11-01 at 11 01 11

**Comment by jacksonh** [comment]
Oops, will move that test change to another branch.

**Comment by jacksonh** [comment]
```
IS IT SAFE to delete the other webhooks file which is under settings. ????? @jacksonh
```
yeah what we will do is add a redirect to the new file, sort of like this: https://github.com/omnivore-app/omnivore/blob/main/packages/web/next.config.js#L41

**Comment by rupin90** [comment]
> ```
> IS IT SAFE to delete the other webhooks file which is under settings. ????? @jacksonh
> ```
> 
> yeah what we will do is add a redirect to the new file, sort of like this: https://github.com/omnivore-app/omnivore/blob/main/packages/web/next.config.js#L41

Right now it does go to the new file from integrations page when we click on the "webhooks" button and the path is `/settings/integrations/webhooks` - I believe that is what we want?
@jacksonh

**Comment by rupin90** [comment]
> Hey @rupin90 how hard would it be on mobile to have the icon above the description? Now that the descriptions are a little longer it doesn't fit very well in mobile.
> 
> I'll also remove the padding on mobile.
> 
> Screen Shot 2022-11-01 at 11 01 11

yeah I can make the change in this PR, should be fairly quick.

**Comment by rupin90** [comment]
> > Hey @rupin90 how hard would it be on mobile to have the icon above the description? Now that the descriptions are a little longer it doesn't fit very well in mobile.
> > I'll also remove the padding on mobile.
> > Screen Shot 2022-11-01 at 11 01 11
> 
> yeah I can make the change in this PR, should be fairly quick.

I have made the necessary changes that would put logo at the top (taking entire row), then text and then button which will take the entire width and row.

**Comment by jacksonh** [comment]
This looks great @rupin what I'll do is point to the old webhooks file for now so we can deploy this, we can change the link in the future when the Webhooks page is better.

**Comment by jacksonh** [comment]
Oh sorry, i see the listing is implemented, just not the button for creating i think

**Pull request merged**
