### PR TITLE
Use chrome-aws-lambda in GCF

### PR DESCRIPTION
**Pull request by jacksonh**
- Use chrome-aws-lambda in GCF
- Remove puppeteer-core package in GCF

### CODE REVIEW

**Comment by jacksonh** [comment]
@sywhb I had to do this to get the GCF deploy to work.

**Comment by sywhb** [comment]
> @sywhb I had to do this to get the GCF deploy to work.

@jacksonh ahh. it's the chromium args again?

**Review by sywhb — APPROVED** [review]

**Comment by sywhb** [comment]
@jacksonh i think the chromium path in env is not right

**Comment by jacksonh** [comment]
@sywhb Yeah I think when run in GCF it sets the path itself, but this package knows the correct paths to use.

**Comment by sywhb** [comment]
@jacksonh yeah i think this package searches through many places so it can find the correct one :)

shall i merge it?

**Pull request merged**
