### PR TITLE
Add cloud function for readability

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Comment by jacksonh** [comment]
NIce, I'm thinking of how this would fit into the flow of slow processing. How would API know to call this one vs doing inline?

**Comment by sywhb** [comment]
> NIce, I'm thinking of how this would fit into the flow of slow processing. How would API know to call this one vs doing inline?

Could we pass a param like `isInline=false` to createArticle API?

**Comment by jacksonh** [comment]
Yeah, that makes sense, but I also wonder, could we put this inside of the `pupeteer-parse` service too? Or maybe wondering, when this finishes readability can we call the API back with the content?

**Comment by sywhb** [comment]
@jacksonh Good idea. I Agree we should put this inside the `puppeteer-parse` service

**Comment by sywhb** [comment]
We could put inline readability in the `puppeteer-parse` service so that after the page is scraped, we could parse the content with inline readability and call the API with parsed content @jacksonh

**Comment by jacksonh** [comment]
Yeah if we ran in puppeteer-parse, then maybe we could send the originalContent and content in the savepage API request. I think we would have to modify it for that though.

**Comment by sywhb** [comment]
I will close this PR and reopen a new one @jacksonh

**Pull request closed without merging**
