### PR TITLE
make library an internal label

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Review by jacksonh — APPROVED** [review]

**Comment by jacksonh** [comment]
One thing I guess we should do is check to see if anyone has this label. I think its probably OK though, since it should be most people's intent, trying to do something similar to this.

**Comment by sywhb** [comment]
> One thing I guess we should do is check to see if anyone has this label. I think its probably OK though, since it should be most people's intent, trying to do something similar to this.

yeah, i think it's okay since it won't affect them.

@jacksonh probably i should also do a db migration to update the existing "library" labels and mark them as "internal"?

**Comment by jacksonh** [comment]
> > One thing I guess we should do is check to see if anyone has this label. I think its probably OK though, since it should be most people's intent, trying to do something similar to this.
> 
> yeah, i think it's okay since it won't affect them.
> 
> @jacksonh probably i should also do a db migration to update the existing "library" labels and mark them as "internal"?

yeah, or at least we can just get an idea of how much its used already first.

**Comment by sywhb** [comment]
@jacksonh i just checked in kibana and we have 94 items labelled with `library` in total

**Pull request merged**
