### PR TITLE
Landing Page Updates - Desktop done

### PR DESCRIPTION
**Pull request by rupin90**
- [x] Landing page update for Desktop
- [x] Landing page update for Mobile

### Images
localhost-3000-about

### CODE REVIEW

**Comment by rupin90** [comment]
@jacksonh  - this is ready for review. Let me know any feedback. Thank you.

**Comment by jacksonh** [comment]
I think there's one issue with this one on mobile. Here's a screenshot you can see the right margin is off
Screen Shot 2022-11-17 at 18 30 08

**Comment by jacksonh** [comment]
There's an issue with the right side of this top image. Maybe we should just stick an actual screenshot in there instead. 

Screen Shot 2022-11-17 at 18 26 18

**Comment by jacksonh** [comment]
Nice, checking this out

**Review by jacksonh — APPROVED** [review]

**Comment by rupin90** [comment]
This should be good now as well!!! @jacksonh  Thank you for reviewing in Details!!!!

**Pull request merged**
