### PR TITLE
Create a content handler for GitHub pages

### PR DESCRIPTION
**Pull request by jacksonh**
This will search for the markdown <article> element and make it
the only page element so we add a repo's README.

### CODE REVIEW

**Comment by sywhb** [comment]
Hah, seems the `GithubHandler` class is not included in this PR

**Comment by jacksonh** [comment]
oops. Classic move for me

**Comment by jacksonh** [comment]
@sywhb Checked in now

**Review by sywhb — APPROVED** [review]
@jacksonh LGTM

**Pull request merged**
