### PR TITLE
Add three new fonts, display fonts in the font selector

### PR DESCRIPTION
**Pull request by jacksonh**

### CODE REVIEW

**Review by satindar — APPROVED** [review]
Pretty cool update! Gonna try out the newsreader font.

**Comment by jacksonh** [comment]
Funny @satindar I did all this research on how to load fonts dynamically like that, implemented a function, then was searching code and saw you already had.

**Comment by satindar** [comment]
> Funny @satindar I did all this research on how to load fonts dynamically like that, implemented a function, then was searching code and saw you already had.

Ha! I remembered doing that when I saw the registerFont calls on this PR. I think it took a lot of trials before it actually worked.

**Comment by jacksonh** [comment]
Yeah pretty crazy way of loading a font. Actually stumbled on an old Marco blog post where he used that to encrypt fonts.

**Pull request merged**
