### PR TITLE
Extension -  Adding Save to Omnivore Toast on Success

### PR DESCRIPTION
**Pull request by rupin90**
### Current Status - 

Screen Shot 2023-01-25 at 9 03 19 PM

This is in progress

 - Functionality

### CODE REVIEW

**Comment by jacksonh** [comment]
Oh nice, you got it to work locally for you?

**Comment by rupin90** [comment]
> Oh nice, you got it to work locally for you?

But after a lot of debugging, multiple codepens to try everything in Javascript and trying to see the connection among the files and what the code is doing. :D

It finally is and I am now going to push changes for the UI with the title and the link to read the article. Will attach a new screenshot.

**Comment by rupin90** [comment]
> Oh nice, you got it to work locally for you? 


Updated the Description as well.

Screen Shot 2022-12-13 at 3 36 25 PM





I remember you mentioned about adding Labels but I am wondering that the toast is open for like 8 seconds as of now. 
Is the next step to add button that takes to the 'Add Labels' URL or
User can add labels in that toast?

**Comment by jacksonh** [comment]
MOst of this one has been incorporated.

**Pull request closed without merging**
