### PR TITLE
fix: change user email address after user deleted account

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Review by jacksonh — COMMENTED** [review]
One question...what happens if they delete twice?

**Comment by sywhb** [comment]
> One question...what happens if they delete twice?

Both accounts would be marked as deleted in db

**Review by jacksonh — APPROVED** [review]

**Comment by jacksonh** [comment]
> > One question...what happens if they delete twice?
> 
> Both accounts would be marked as deleted in db

but would there be a conflict if they had the same email?

**Review by jacksonh — APPROVED** [review]

**Comment by sywhb** [comment]
> > > One question...what happens if they delete twice?
> > 
> > 
> > Both accounts would be marked as deleted in db
> 
> but would there be a conflict if they had the same email?

the `user_id` of each account would be different

**Pull request merged**
