### PR TITLE
Feature 1079 -Updating list view to the latest design

### PR DESCRIPTION
**Pull request by rupin90**
- [x] Adding Author
- [x] Adding origin
- [x] Adding Card menu

### Design -
Screen Shot 2022-08-24 at 12 45 14 AM

### CODE REVIEW

**Comment by jacksonh** [comment]
Whaaaa. So fast

**Comment by rupin90** [comment]
> Whaaaa. So fast

haha no it wasn't ready.

**Comment by rupin90** [comment]
@jacksonh  - Let me know if this is what was all needed. It seemed like most of the components were there just some CSS was needed to match the design. Let me know any feedback. Thank you.

**Comment by jacksonh** [comment]
This is what I am seeing locally:

Screen Shot 2022-08-29 at 12 03 34

Looks like image layout and maybe author name are the main issues.

**Comment by rupin90** [comment]
@jacksonh  
- So I updated the view with the condition that image won't be displayed if it is List Layout.  So for the Grid Layout the image for the card will be displayed. 
- I have increased the font weight for the author and updated the margin around. 
- There is a pop up menu for both Grid and List layout.


I think this PR now fixes the necessary changes for both Grid and List layout according to the design.

**Comment by rupin90** [comment]
Merging this should tackle 1079 and 1097 github issues.

**Comment by jacksonh** [comment]
Looks good. There actually is a design for a version with images too, but lets merge this one. I think we might tweak a bit in design also. Maybe can tighten it up a little bit and make it more compact.

**Review by jacksonh — APPROVED** [review]

**Pull request merged**
