### PR TITLE
[Omn-585] - Onboarding Pages 1, 4, 5, and 6.

### PR DESCRIPTION
**Pull request by gitstart-omnivore**
## Description

This PR contains 4 new onboarding pages.
- onboarding/01.
- onboarding/04.
- onboarding/05.
- onboarding/06.

## House Keeping
- [x] Added Loom video ?
- [x] Is Deployment Link passing ?
- [x] Have you assinged PR to yourself ?
- [x] Is Github action passing ?
- [x] Updated the appropriate tag ?

## Ticket link (if applicable)

[Task Link for onboarding page 01](https://app.gitstart.com/tasks/55316) 
[Task Link](https://app.gitstart.com/clients/omnivore/tickets/OMN-585)
[Loom Video](https://www.loom.com/share/f6b14638d6e14a7587e190ca7815359a)

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Others

## Checklist:

- [x] I have test my code on different browsers and devices to make sure it is cross-browser compatible (both desktop and mobile).
- [x] I have confirmed design matches Spec specified on Figma.

## Remarks

- [ ] I added a new package to achieve this task.
- [ ] I have updated package.json

### CODE REVIEW

**Comment by gitstart-omnivore** [comment]
Hi @jacksonh, We need page description for the following pages.
- [04](https://github.com/omnivore-app/omnivore/issues/583)
- [05](https://github.com/omnivore-app/omnivore/issues/584)

Thanks!

**Comment by gitstart-omnivore** [comment]
We have also changed the layout of the storybook for onboarding pages so that all the onboarding pages appear under one heading. This way storybook will look cleaner.

**Comment by jacksonh** [comment]
It looks like there's a layout issue on screen six in the mobile view.

Screen Shot 2022-05-20 at 13 29 53

**Review by jacksonh — CHANGES_REQUESTED** [review]
Just that last screen that seems to have issues on mobile

**Comment by gitstart-omnivore** [comment]
@jacksonh This issue should be fixed now.

**Comment by jacksonh** [comment]
@gitstart it seems like there are problems with the diff on this one. for example you can see changes in `apple` here

**Comment by gitstart-omnivore** [comment]
@jacksonh We have fixed the diff as well.

**Pull request merged**
