### PR TITLE
[Omn-382] - Updated landing page

### PR DESCRIPTION
**Pull request by gitstart-omnivore**
## Spec Checklist
- [x] Does the figma design fit the ticket description ?

## Description

Based on Figma design here we have an updated landing page. This page should be built as /landing for now.

Figma designs:

-- Desktop: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=287%3A31514
-- Mobile: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=287%3A34213

Desktop:

[Screen Shot 2022-04-04 at 22 21 38](https://user-images.githubusercontent.com/75189/161684304-e3fa1679-2817-463d-9fa3-26ebfe82fe64.png)

Mobile:

[Screen Shot 2022-04-04 at 22 21 51](https://user-images.githubusercontent.com/75189/161684333-fcbf1c8b-276f-459d-b85e-384ce968ab1c.png)

Note how the design is divided into sections:

Simply reader-friendly
Make it your own
A better way to share
Discover new content
We will want to be able to enable/disable some of these sections, so they should be treated as separate pieces as we build.

#382 

## House Keeping
- [x] Added Loom video ?
- [ ] Is Deployment Link passing ?
- [x] Have you assinged PR to yourself ?
- [ ] Is Github action passing ?
- [x] Updated the appropriate tag ?

## Ticket link (if applicable)

[Task Link](https://app.gitstart.com/clients/omnivore/tickets/OMN-382)

## How has this been tested?

Go to "localhost:3000/landing" page.

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Others

## Checklist:

- [x] I have confirmed design matches Spec specified on Figma.

## Loom Video
https://www.loom.com/share/5c3f51dc22174eff8e6b390c3600032e

### CODE REVIEW

**Review by jacksonh — CHANGES_REQUESTED** [review]
It looks like there are some linting failures on this one. Can you test with `yarn lint --fix`

**Comment by gitstart-omnivore** [comment]
@jacksonh Apologies, This has been fixed. Thanks!

**Comment by jacksonh** [comment]
It seems like the main colours are a little off. Here is a screenshot of ours on the left, and figma on the right. The main background colour looks different, the top header color is white instead of black

Screen Shot 2022-04-12 at 11 21 35

**Comment by jacksonh** [comment]
For these icons on the bottom, lets use the phosphor icons instead of PNGs. They look a little blurry here because the PNGs aren't available in multiple resolutions.

Screen Shot 2022-04-12 at 11 25 33

**Comment by jacksonh** [comment]
Four links to add here (don't have the Android one yet)


Screen Shot 2022-04-12 at 11 27 05

1. `/login`
2. https://twitter.com/OmnivoreApp
3. https://github.com/omnivore-app/omnivore
4. https://discord.gg/h2z5rppzz9
5. https://omnivore.app/install/ios

**Comment by gitstart-omnivore** [comment]
Hi @jacksonh, We have removed the theme colors, added phosphor icons and links. The google play button has been commented out.

**Comment by jacksonh** [comment]
Ah I figured out the colour issue I was seeing is because of light/dark theme. We have this css `color-scheme: light dark;` which causes the issue. Looking into a fix.

**Comment by jacksonh** [comment]
Sorry two last small things on this one:

1. with figma i think we can export two resolutions of images, so we have the 1x and 2x versions. Usually we want both versions in the report and then the `<img` should look something like below. That will choose the appropriate version based on the user's screen density. 

```
  <img srcSet="/static/images/mobile-app-preview.png, /static/images/mobile-app-preview@2x.png 2x" />
``` 

2. There are a few images we can remove from the PR now, the social ones (discord, github, twitter) are all included via phosphur so we don't need the PNGs

**Comment by gitstart-omnivore** [comment]
@jacksonh This has been done as well, Thanks!

**Pull request merged**
