### PR TITLE
[OMN-617] - Align AppStore button to right on small screens in MobileInstallComponent

### PR DESCRIPTION
**Pull request by gitstart-omnivore**
## Description

Aligned Appstore icon on MobileInstallHelp component to the right and created storybook story for it.
[Loom Video](https://www.loom.com/share/8d0b2040069b40849eadfcc5f579396f)

## House Keeping
- [x] Added Loom video ?
- [x] Is Deployment Link passing ?
- [x] Have you assinged PR to yourself ?
- [x] Is Github action passing ?
- [x] Updated the appropriate tag ?

## Ticket link (if applicable)

[Task Link](https://app.gitstart.com/clients/omnivore/tickets/OMN-617)

## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [x] Others

## Checklist:

- [x] I have test my code on different browsers and devices to make sure it is cross-browser compatible (both desktop and mobile).
- [x] I have confirmed design matches Spec specified on Figma.

## Remarks

- [ ] I added a new package to achieve this task.
- [ ] I have updated package.json

### CODE REVIEW

**Comment by gitstart-omnivore** [comment]
@jacksonh This has been fixed.

**Comment by jacksonh** [comment]
It looks like some other changes to this component were lost here. See in the second screenshot how the Learn More was moved down to the bottom? We recently made that change to make it easier to tap.

Screenshot with this change:

Screen Shot 2022-05-16 at 15 37 49


Current main:

Screen Shot 2022-05-16 at 15 38 28

**Comment by gitstart-omnivore** [comment]
@jacksonh Hmm, It seems like we do have it. The text is "Learn more about the share extension here" and it only displays for large screens.

We will change the change the text. Do we also change it to display for smaller screens as well?

**Comment by gitstart-omnivore** [comment]
@jacksonh Not sure how this happened, but we cloned from main and it seems to exist in our branch.

But the text in our branch is "Learn more about the share extension here." instead of "Learn more about the iOS app ->". We will change that as well.

**Comment by jacksonh** [comment]
Huh, this is how it looks for small screens in production now:

Screen Shot 2022-05-16 at 16 04 14

**Comment by gitstart-omnivore** [comment]
@jacksonh Do we want the "Learn more about the iOS app ->" text to appear for mobile screens along with the "Learn More" text at the top?

**Comment by gitstart-omnivore** [comment]
> Huh, this is how it looks for small screens in production now:
> 
> Screen Shot 2022-05-16 at 16 04 14

Hmm, that's weird, even the "Learn more about the iOS app ->" only appears for large screens in our branch.

**Comment by gitstart-omnivore** [comment]
@jacksonh, We have made some changes to this component.

This is how it looks for mobile now.
Screenshot_1

The "Learn More" seems to be missing from Browser Extensions component, Is that on-purpose or do we add it there as well?

**Pull request merged**
