### PR TITLE
[Omn-190] - [Settings View] - Labels

### PR DESCRIPTION
**Pull request by gitstart-omnivore**
## Spec Checklist
- [ ] Are Api endpoints ready and properly documented ?
- [ ] Does the figma design fit the ticket description ?
- [ ] Added video describing your plan of action ?

## Description

This is part of the base issue [Settings View](https://github.com/omnivore-app/omnivore/issues/193)

Omnivore allows users to create labels and attach them to library items. A label has a name, colour, and description , users can create labels, delete labels. They can also edit a labels color and description.

This page has a temporary version available at settings/labels
## House Keeping
- [ ] Added video describing your plan of action ?
- [ ] Added Loom video ?
- [ ] Is Deployment Link passing ?
- [x] Have you assinged PR to yourself ?
- [ ] Is Github action passing ?
- [x] Updated the appropriate tag ?

## Ticket link (if applicable)

[Task Link](https://app.gitstart.com/clients/omnivore/tickets/OMN-190)

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Others

## Checklist:

- [ ] I have test my code on different browsers and devices to make sure it is cross-browser compatible (both desktop and mobile).
- [ ] I have confirmed the payload for integrated API matches params on API docs
- [ ] I have confirmed design matches Spec specified on Figma.

## Language translation

- [ ] Did you udpate/add a new text node ?
- [ ] I have updated language mapping JSOn in locale

## Remarks

- [x] I added a new package to achieve this task.
- [x] I have updated package.json

### CODE REVIEW

**Comment by gitstart-omnivore** [comment]
@jacksonh this PR is ready for review, except we noticed the label update functionality wasn't implemented. We've implemented it though, but this permission error occurs when we try to update the labels, is there something we're missing?

Screenshot 2022-03-30 at 13 23 29

Please kindly take a look

**Comment by jacksonh** [comment]
> @jacksonh this PR is ready for review, except we noticed the label update functionality wasn't implemented. We've implemented it though, but this permission error occurs when we try to update the labels, is there something we're missing?
> 
> Screenshot 2022-03-30 at 13 23 29
> 
> Please kindly take a look

Ah thank you, this issue is because of the row level security attributes. I'll push a fix while reviewing.

**Comment by jacksonh** [comment]
The text in the `Create Label` button isn't quite vertically centered properly. A couple extra pixels at the bottom I think. 

Screen Shot 2022-03-30 at 13 31 29

**Comment by jacksonh** [comment]
It looks like these buttons are a little too big, the figma is on the right and the implementation on the left.

Screen Shot 2022-03-30 at 13 34 15

**Comment by jacksonh** [comment]
This dropdown needs to be a fixed width, otherwise when you are changing colours it will "jitter" as the values are changed and it resizes\

Screen Shot 2022-03-30 at 13 47 05

**Comment by jacksonh** [comment]
Here's a quick video that shows two issues, the first is the custom color modal moving around when trying to select a custom colour. The second issue is the one I mentioned above, the box jittering around when the colour value is changed:

https://www.loom.com/share/7164c2db62c341b19cda02863c2694b0

**Comment by jacksonh** [comment]
We should try to centre these headers over the items. Name looks ok, but description, color, actions aren't centred right

Screen Shot 2022-03-30 at 13 56 49

**Comment by jacksonh** [comment]
> We should try to centre these headers over the items. Name looks ok, but description, color, actions aren't centred right
> 
> Screen Shot 2022-03-30 at 13 56 49

Actually, lets ignore this and instead of centering we can left align everything.

**Comment by gitstart-omnivore** [comment]
@jacksonh we've effected the review corrections, please can you take a look?

**Comment by jacksonh** [comment]
This one is looking good. I'm going to play around tomorrow with how the edit functions work, but its good to go.

**Review by jacksonh — APPROVED** [review]

**Pull request merged**
