### PR TITLE
Improve keyboard shortcuts modal 

### PR DESCRIPTION
**Pull request by cdev147**
Better Model so that code looks cleaner

### CODE REVIEW

**Comment by cdev147** [comment]
> Thanks, one issue is it looks like a different prettier config. If you'd like I can try running ours (the main thing i notice is the semicolons.

yes sure, also let me know if I can help for the same as I have just started open source and it would help me grow.

**Comment by jacksonh** [comment]
> > Thanks, one issue is it looks like a different prettier config. If you'd like I can try running ours (the main thing i notice is the semicolons.
> 
> yes sure, also let me know if I can help for the same. @jacksonh should I remove the semi colons?

Have you used prettier before? If you are using Visual Studio code it should format it according to our coding standards for you. But sometimes it takes some manual setup.

**Comment by jacksonh** [comment]
What i am going to do is merge this, then run prettier locally, then create a new PR.

However, I think this is mostly a cosmetic code change.

**Comment by jacksonh** [comment]
Actually, I need to back this one out. It was hard to tell with the prettier changes but this isn't valid:

```
const initalKeyMapping = useMemo(
    () => useInitialKeyMapping(commands),
    [commands]
  )
```

you get this error:

```
64:11  Error: React Hook "useInitialKeyMapping" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.  react-hooks/rules-of-hooks
```

**Pull request merged**
