### PR TITLE
Fix password in README

### PR DESCRIPTION
**Pull request by dentropy**
Fix password in readme, password is demo_password not demo, see packages/db/setup.sh for reference

### CODE REVIEW

**Comment by jacksonh** [comment]
Thanks!

**Comment by Hrishikesh156** [comment]
@jacksonh I'm unable to login with demo@omnivore.app, password: demo_password. Do I need to run any other command than docker compose up
image

**Comment by dentropy** [comment]
@Hrishikesh156 You need to make sure the migrations ran for the postgres database, see the omnivore-migrate docker container that was run

image

**Comment by dentropy** [comment]
@Hrishikesh156 you can check if the database migrations ran by running the following commands,

``` bash

docker exec -it omnivore-postgres bash
psql -d omnivore -U app_user
\dt
exit
psql -d omnivore -U postgres
\dt
select * from schemaversion;

```

image

**Comment by Hrishikesh156** [comment]
@dentropy from docker ps -a, I guess the migrations ran for the postgres database

image

Apparently it couldn't find any relations in the omnivore database

image

**Pull request merged**
