### PR TITLE
Increase luminous for labels

### PR DESCRIPTION
**Pull request by rupin90**
Leveraging color2k library for some color conversion methods.

It is still not the best view but it does generate a lighter shade if luminance value is below 0.5.  I have also tried to do HSL values conversions and all but it would completely change the color not really make it glowy. Lot of conversions and lot of code but the output is not exactly how we want it to be.

### CODE REVIEW

**Comment by jacksonh** [comment]
i think the light mode is really good now. The one issue I see is dark mode. When the label color is too dark I think we need to switch to a tinted white text.

**Comment by rupin90** [comment]
I have been looking to see if there is anyway to lighten it up, I have played around with HSLA and RGBA, its not increasing the readability.

Yeah tinted :D

**Comment by jacksonh** [comment]
Screenshot of GitHub dark mode

Screen_Shot_2022-07-11_at_16 09 41

**Review by jacksonh — APPROVED** [review]
Fantastic improvement. Just need to update to less lightening `lighten(props.color, 0.2)`

**Comment by rupin90** [comment]
🙏🏽

**Pull request merged**
