### PR TITLE
Create apple/Resources/zh-Hans.lproj/LaunchScreen.strings

### PR DESCRIPTION
**Pull request by holton-jiang**
This is part Chinese Simplified translation.

### CODE REVIEW

**Comment by jacksonh** [comment]
Excellent thank you.

**Comment by jacksonh** [comment]
@holton-jiang can you click through on the CLA above? Let me know if you need help understanding it.

**Comment by holton-jiang** [comment]
> @holton-jiang can you click through on the CLA above? Let me know if you need help understanding it.

I have clicked on CLA.

**Comment by jacksonh** [comment]
Awesome, I will try and add this to the next iOS build (hopefully in Test Flight today)

**Comment by holton-jiang** [comment]
> Awesome, I will try and add this to the next iOS build (hopefully in Test Flight today)

Thank you for your help.

**Comment by jacksonh** [comment]
I'm not sure if you are in our Discord, but if you are I usually post there when we have new builds available.

**Comment by holton-jiang** [comment]
> I'm not sure if you are in our Discord, but if you are I usually post there when we have new builds available.

Sorry, I can't use Discord here

**Comment by jacksonh** [comment]
I'll post Test Flight info here if you want to try the new build when it is up.

**Comment by holton-jiang** [comment]
> 

Ok, I'll try it and wish you a Happy New Year too.

**Pull request merged**
