### PR TITLE
Fix/1096 - Added line seprator above labels and subscriptions

### PR DESCRIPTION
**Pull request by rupin90**
Merging 1091 and 1092 fixes before would make this PR look correct.

### CODE REVIEW

**Comment by jacksonh** [comment]
Hey Rupin, I think there's one small issue with this. The borders extends all the way to the right for me, and is maybe a bit to far on the left. I think its kind of a pain to fix this because we can't just use border...right?

Screen Shot 2022-08-19 at 13 29 53

**Comment by rupin90** [comment]
> Hey Rupin, I think there's one small issue with this. The borders extends all the way to the right for me, and is maybe a bit to far on the left. I think its kind of a pain to fix this because we can't just use border...right?
> 
> Screen Shot 2022-08-19 at 13 29 53

Apparently even after a decade of Frontend legendary change/ upgrade in the world, CSS never got the `border-length` kinda property. 🤷🏽 . lol.

Used an alternative to control the border length, I believe this should work.

CC: @jacksonh

**Review by jacksonh — APPROVED** [review]

**Comment by jacksonh** [comment]
CSS!

**Comment by jacksonh** [comment]
@rupin90 is there an easy way to add a little more padding between `Newsletters` and `Labels`? I think it just needs 2px more maybe. It feels a little too tight, but otherwise this is good. We can try to do that separately.

**Review by jacksonh — APPROVED** [review]

**Comment by rupin90** [comment]
> @rupin90 is there an easy way to add a little more padding between `Newsletters` and `Labels`? I think it just needs 2px more maybe. It feels a little too tight, but otherwise this is good. We can try to do that separately.

Will do that separately

**Pull request merged**
