### PR TITLE
Add The Atlantic handler to avoid paywall and correctly format

### PR DESCRIPTION
**Pull request by Podginator**
Added a handler to parse the Atlantic content, and fixed a small issue where the line-height would not be correctly considered. 

I believe the actual issue is in a CSS property, but I didn't know whether or not that was used elsewhere and so instead I changed the article to a div.

### CODE REVIEW

**Comment by jacksonh** [comment]
I'll run `yarn lint --fix` on this in a bit, i think that should clean up the linting errors.

**Comment by Podginator** [comment]
Made a few changes to remove stuff unrelated to the specific article. I find that they break up the flow of the article when reading on a Read-it-later app.

**Comment by jacksonh** [comment]
Looks like I need to lint again, should get this merged and deployed today though.

**Comment by jacksonh** [comment]
NIce, should be in prod in a few hours. Thank you!

**Pull request merged**
