### PR TITLE
Stop throwing error and return empty speech if there is no content in the article

### PR DESCRIPTION
**Pull request by sywhb**
This should fix the Sentry report here: https://sentry.io/organizations/omnivore/issues/3581522996/?project=5591542&query=is%3Aunresolved

### CODE REVIEW

**Comment by jacksonh** [comment]
Is this happening with PDFs or something?

**Review by jacksonh — APPROVED** [review]

**Comment by sywhb** [comment]
> Is this happening with PDFs or something?

Yes, it's the PDF

**Comment by jacksonh** [comment]
Creating a testflight build from this

**Comment by jacksonh** [comment]
Oops, comment on the wrong PR!

**Pull request merged**
