### PR TITLE
Update the default Highlights query

### PR DESCRIPTION
**Pull request by jacksonh**
This query is more of what people want, all their created
highlights, not just ones in their current inbox. Since a normal
workflow would be: read + highlight, archive, review highlights.

### CODE REVIEW

**Comment by jacksonh** [comment]
This will be a pretty big update for the database so I'm not sure if we should run it outside the deploy

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/issues/3298

**Comment by jacksonh** [comment]
@sywhb we can discuss this in discord, I feel like psql should run it fine but maybe i should run some batches outside of the deploy

**Comment by jacksonh** [comment]
There is a race condition here too. When we deploy the migration will be run, then any new users that are created before the the backend is deployed will have the old version. So we need to re-run the update.

**Comment by sywhb** [comment]
> There is a race condition here too. When we deploy the migration will be run, then any new users that are created before the the backend is deployed will have the old version. So we need to re-run the update.

nice catch. probably we should move the default filters logic to the database like creating a function/trigger @jacksonh

**Comment by jacksonh** [comment]
Yeah that would be good.

**Pull request merged**
