### PR TITLE
make readingProgress required in the elastic page data

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Comment by jacksonh** [comment]
Great, with this can we delete from the `function_resolvers`?

**Comment by sywhb** [comment]
> Great, with this can we delete from the `function_resolvers`?

@jacksonh Yes, we can delete them from `function_resolvers` since they are stored in elastic

**Comment by sywhb** [comment]
@jacksonh Oh I will run an update query in elastic to update those null readingProgress to 0 first.

So we won't have trouble with the new pages added yesterday

**Review by jacksonh — APPROVED** [review]

**Comment by sywhb** [comment]
@jacksonh I have added `readingProgressPercent=0` and `readingProgressAnchorIndex=0` to the pages in elastic where `readingProgressPercent` and `readingProgressAnchorIndex` don't exist.

**Pull request merged**
