### PR TITLE
Use search API to filter page in rule engine

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Review by jacksonh — APPROVED** [review]
This looks good to me, how do you feel about it now that implementing?

**Comment by sywhb** [comment]
I feel more confident now. 
I also made a small change to run the filter for each rule before calling actions and have a `Promise.all` for all the actions; so the actions will not be affected by each other.

**Comment by jacksonh** [comment]
Oh the promise.all thing is really nice, in the future we could probably add a special token to bypass rate limiting.

**Comment by sywhb** [comment]
Yeah, rate-limiting is a pain in the arse. Maybe for now we only allow max 10 rules per user?

**Pull request merged**
