### PR TITLE
Fix - Grid and List Layout

### PR DESCRIPTION
**Pull request by rupin90**
### 
_Its in Progress,
I tried to create the two separate layouts for grid and List but somehow the layout passed  in the <LibraryGridCard....> Component is always GRID layout so I cannot render them based on condition that whether it is a grid layout or list layout._  

### Screenshots - 

Screen Shot 2022-10-06 at 12 50 23 PM

Screen Shot 2022-10-06 at 12 50 17 PM

### CODE REVIEW

**Comment by satindar** [comment]
> Just seeing this error:
> 
> ```
> 
> 
> 
> 
> ./components/templates/library/LibrarySearchBar.tsx:169:68
> 02:07:20.477 | Type error: Argument of type 'string' is not assignable to parameter of type 'never'.
> 02:07:20.477 |  
> 02:07:20.477 | 167 \|                 {isOpen &&
> 02:07:20.478 | 168 \|                   recentSearches
> 02:07:20.478 | > 169 \|                     .filter((item) => !inputValue \|\| item.includes(inputValue))
> 02:07:20.478 | \|                                                                    ^
> 02:07:20.478 | 170 \|                     .map((item, index) => (
> 02:07:20.478 | 171 \|                       <SpanBox
> 02:07:20.478 | 172 \|                         {...getMenuProps()}
> 02:07:20.514 | error Command failed with exit code 1.
> 02:07:20.514 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 02:07:20.531 | error Command failed.
> 02:07:20.531 | Exit code: 1
> 02:07:20.532 | Command: /node14/bin/node
> 02:07:20.532 | Arguments: /vercel/.yarn/lib/cli.js build
> 02:07:20.532 | Directory: /vercel/path0/packages/web
> 02:07:20.532 | Output:
> 02:07:20.532
> 
> <br class="Apple-interchange-newline">
> ```

@rupin90 This one will be fixed with a rebase

**Comment by rupin90** [comment]
> > Just seeing this error:
> > ```
> > 
> > 
> > 
> > 
> > ./components/templates/library/LibrarySearchBar.tsx:169:68
> > 02:07:20.477 | Type error: Argument of type 'string' is not assignable to parameter of type 'never'.
> > 02:07:20.477 |  
> > 02:07:20.477 | 167 \|                 {isOpen &&
> > 02:07:20.478 | 168 \|                   recentSearches
> > 02:07:20.478 | > 169 \|                     .filter((item) => !inputValue \|\| item.includes(inputValue))
> > 02:07:20.478 | \|                                                                    ^
> > 02:07:20.478 | 170 \|                     .map((item, index) => (
> > 02:07:20.478 | 171 \|                       <SpanBox
> > 02:07:20.478 | 172 \|                         {...getMenuProps()}
> > 02:07:20.514 | error Command failed with exit code 1.
> > 02:07:20.514 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > 02:07:20.531 | error Command failed.
> > 02:07:20.531 | Exit code: 1
> > 02:07:20.532 | Command: /node14/bin/node
> > 02:07:20.532 | Arguments: /vercel/.yarn/lib/cli.js build
> > 02:07:20.532 | Directory: /vercel/path0/packages/web
> > 02:07:20.532 | Output:
> > 02:07:20.532
> > 
> > <br class="Apple-interchange-newline">
> > ```
> 
> @rupin90 This one will be fixed with a rebase

Thank you :) @satindar.

**Comment by rupin90** [comment]
> > Just seeing this error:
> > ```
> > 
> > 
> > 
> > 
> > ./components/templates/library/LibrarySearchBar.tsx:169:68
> > 02:07:20.477 | Type error: Argument of type 'string' is not assignable to parameter of type 'never'.
> > 02:07:20.477 |  
> > 02:07:20.477 | 167 \|                 {isOpen &&
> > 02:07:20.478 | 168 \|                   recentSearches
> > 02:07:20.478 | > 169 \|                     .filter((item) => !inputValue \|\| item.includes(inputValue))
> > 02:07:20.478 | \|                                                                    ^
> > 02:07:20.478 | 170 \|                     .map((item, index) => (
> > 02:07:20.478 | 171 \|                       <SpanBox
> > 02:07:20.478 | 172 \|                         {...getMenuProps()}
> > 02:07:20.514 | error Command failed with exit code 1.
> > 02:07:20.514 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > 02:07:20.531 | error Command failed.
> > 02:07:20.531 | Exit code: 1
> > 02:07:20.532 | Command: /node14/bin/node
> > 02:07:20.532 | Arguments: /vercel/.yarn/lib/cli.js build
> > 02:07:20.532 | Directory: /vercel/path0/packages/web
> > 02:07:20.532 | Output:
> > 02:07:20.532
> > 
> > <br class="Apple-interchange-newline">
> > ```
> 
> This is an old problem.
> 
> I have a weird interesting issue that is hard to know what's happening. We have two layouts and I tried to separate these layouts based on whether it is a GRID_LAYOUT or LIST_LAYOUT, apparently the value received in the component is always GRID 🤷🏽

IGNORE the previous - all issues are fixed and cleaned up CSS. This is PR ready !! phew

**Comment by jacksonh** [comment]
Going to re-run tests here. Not sure why they failed.

**Review by jacksonh — APPROVED** [review]

**Comment by rupin90** [comment]
> Going to re-run tests here. Not sure why they failed.

Thank you!! Going to merge this now!

**Pull request merged**
