### PR TITLE
Remove Wiggle effect on sub menu items

### PR DESCRIPTION
**Pull request by rupin90**
Video - https://www.awesomescreenshot.com/video/10530477?key=255b3044b9042920babea8053182e3d8

### CODE REVIEW

**Comment by jacksonh** [comment]
Hey @rupin90 can you use the naming convention `feat/1074` for your branches? we usually just use `feat` or `fix`, for a new feature or for a fix.

**Comment by jacksonh** [comment]
With this one it looks like the background colour of submenus isn't being set correctly:

Screen Shot 2022-08-16 at 17 14 51

**Review by jacksonh — CHANGES_REQUESTED** [review]
I think we need to do something to set the background of the submenu section to `var(--colors-libraryBackground)`

**Comment by rupin90** [comment]
> I think we need to do something to set the background of the submenu section to `var(--colors-libraryBackground)`

hmm, interesting. Let me look into this

**Comment by rupin90** [comment]
> Hey @rupin90 can you use the naming convention `feat/1074` for your branches? we usually just use `feat` or `fix`, for a new feature or for a fix.

Sounds good, will do that onwards for my branches.


Any feedback on this PR is addressed and updated the video for reference ✌🏽 

cc: @jacksonh

**Comment by jacksonh** [comment]
Looks good!

**Review by jacksonh — APPROVED** [review]

**Pull request merged**
