### PR TITLE
Feature/search highlights web

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Comment by sywhb** [comment]
`diff` result:

```
git diff feature/search-highlights-web..feature/search-highlights --name-only

docker-compose-test.yml
packages/api/.env.example
packages/api/.env.test
packages/api/Dockerfile-test
packages/api/add_highlight_to_elastic.py
packages/api/elastic_migrate.py
packages/api/index_settings.json
packages/api/package.json
packages/api/src/datalayer/links/share_info.ts
packages/api/src/elastic/highlights.ts
packages/api/src/elastic/index.ts
packages/api/src/elastic/labels.ts
packages/api/src/elastic/pages.ts
packages/api/src/elastic/types.ts
packages/api/src/generated/graphql.ts
packages/api/src/generated/schema.graphql
packages/api/src/resolvers/article/index.ts
packages/api/src/resolvers/function_resolvers.ts
packages/api/src/resolvers/highlight/index.ts
packages/api/src/resolvers/labels/index.ts
packages/api/src/resolvers/links/index.ts
packages/api/src/routers/svc/content.ts
packages/api/src/routers/svc/pdf_attachments.ts
packages/api/src/schema.ts
packages/api/src/services/create_page_save_request.ts
packages/api/src/services/labels.ts
packages/api/src/services/reports.ts
packages/api/src/services/save_email.ts
packages/api/src/services/save_file.ts
packages/api/src/services/save_page.ts
packages/api/src/utils/search.ts
packages/api/test/elastic/index.test.ts
packages/api/test/global-setup.ts
packages/api/test/global-teardown.ts
packages/api/test/resolvers/article.test.ts
packages/api/test/resolvers/highlight.test.ts
packages/api/test/resolvers/labels.test.ts
packages/api/test/routers/pdf_attachments.test.ts
packages/api/test/services/save_email.test.ts
packages/api/test/services/save_newsletter_email.test.ts
packages/api/test/util.ts
```

**Comment by sywhb** [comment]
this contains only web changes of PR: #339

**Comment by jacksonh** [comment]
Created a ticket to update this to the latest design for highlight cards: https://github.com/omnivore-app/omnivore/issues/437

**Comment by jacksonh** [comment]
Rebased and pull the HighlightCard files in from https://github.com/omnivore-app/omnivore/pull/492

**Pull request merged**
