### PR TITLE
Omn 437: [Highlight cards in the library view]

### PR DESCRIPTION
**Pull request by gitstart-omnivore**
## Description
Omnivore has a new endpoint for library search, that can return highlights instead of just pages. This lets users search for all their highlights in the main library instead of just pages.

## House Keeping
- [x] Added Loom video?
- [x] Is Deployment Link passing?
- [x] Have you assigned PR to yourself?
- [x] Is Github action passing?
- [x] Updated the appropriate tag?

## Ticket link (if applicable)
[Task Link](https://app.gitstart.com/clients/omnivore/tickets/OMN-437)
[Soapbox Link](https://soapbox.wistia.com/videos/wTzxfMO4I7)

## Types of changes

- [ ] Bug fix
- [x] New feature
- [x] Refactor
- [ ] Others

## Checklist:

- [x] I have test my code on different browsers and devices to make sure it is cross-browser compatible (both desktop and mobile).
- [x] I have confirmed design matches Spec specified on Figma.

## Remarks

- [ ] I added a new package to achieve this task.
- [ ] I have updated package.json

### CODE REVIEW

**Review by jacksonh — CHANGES_REQUESTED** [review]
Can we add a storybook story for the highlight card?

**Comment by gitstart-omnivore** [comment]
@jacksonh We have added the story.

**Comment by gitstart-omnivore** [comment]
@jacksonh We have also removed the HiglightImage component.

**Comment by jacksonh** [comment]
I've folded these changes into https://github.com/omnivore-app/omnivore/pull/396 so I will close this one out.

**Pull request closed without merging**
