### PR TITLE
Add LABEL_ADDED as event type in webhooks

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Comment by jacksonh** [comment]
Hey @sywhb sorry I can't tell from this, but this will be fired when a label is added to a page?

**Comment by sywhb** [comment]
@jacksonh, yeah, it should, because we publish `LABEL_CREATED` event to the pubsub queue when there is a label added to some page.

It's the best to test it in demo first

**Comment by jacksonh** [comment]
Ah thanks, i wasn't quite sure if `LABEL_CREATED` was when a label was first created.

**Comment by sywhb** [comment]
> Ah thanks, i wasn't quite sure if `LABEL_CREATED` was when a label was first created.

Haha, sounds weird right? I, at that time, thought there should be such event for `label_added` instead of `label_created` but probably we should have both 👍

**Review by jacksonh — APPROVED** [review]
LETS GO!

**Pull request merged**
