### PR TITLE
[Omn-192] - Settings View(Installation)

### PR DESCRIPTION
**Pull request by gitstart-omnivore**
## Spec Checklist
- [ ] Does the figma design fit the ticket description ?
- [ ] Are Api endpoints ready and properly documented ?
- [x] Added video describing your plan of action ?

## Description
 - Omnivore has an installation page that helps users installed native apps (iOS and Mac) and browser extensions. The current version is available at /settings/installation. We have a temporary version of this page, but need to update to the new design / layout.
 - Added the tooltip and the select component.

## House Keeping
- [x] Added video describing your plan of action ?
- [x] Added Loom video ?
- [ ] Is Deployment Link passing ?
- [x] Have you assinged PR to yourself ?
- [x] Is Github action passing ?
- [x] Updated the appropriate tag ?

## Ticket link (if applicable)
[Task Link](https://app.gitstart.com/clients/omnivore/tickets/OMN-192)

## How has this been tested?
I have checked it on multiple screen size

## Types of changes

- [ ] Bug fix
- [ ] New feature
- [x] Refactor
- [ ] Others

## Checklist:

- [ ] I have test my code on different browsers and devices to make sure it is cross-browser compatible (both desktop and mobile).
- [ ] I have confirmed the payload for integrated API matches params on API docs
- [x] I have confirmed design matches Spec specified on Figma.

## Language translation

- [ ] Did you udpate/add a new text node ?
- [ ] I have updated language mapping JSOn in locale

## Remarks

- [x] I added a new package to achieve this task.
- [x] I have updated package.json

### CODE REVIEW

**Comment by jacksonh** [comment]
Looks like some missing properties:


```


14:10  Error: Unknown property 'clip-path' found, use 'clipPath' instead  react/no-unknown-property
--
11:37:05.090 | 51:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.090 | 52:28  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.090 | 62:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
11:37:05.090 | 63:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
11:37:05.090 | 74:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.090 | 75:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.090 | 76:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.090 | 77:28  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.090 | 87:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
11:37:05.090 | 88:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
11:37:05.091 | 99:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.091 | 100:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.091 | 101:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.091 | 102:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.091 | 103:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.091 | 113:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.091 | 114:28  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
11:37:05.091 | 114:49  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
```

**Comment by gitstart-omnivore** [comment]
> Looks like some missing properties:
> 
> ```
> 
> 
> 14:10  Error: Unknown property 'clip-path' found, use 'clipPath' instead  react/no-unknown-property
> --
> 11:37:05.090 | 51:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.090 | 52:28  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.090 | 62:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
> 11:37:05.090 | 63:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
> 11:37:05.090 | 74:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.090 | 75:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.090 | 76:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.090 | 77:28  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.090 | 87:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
> 11:37:05.090 | 88:31  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
> 11:37:05.091 | 99:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.091 | 100:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.091 | 101:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.091 | 102:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.091 | 103:31  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.091 | 113:17  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.091 | 114:28  Error: Unknown property 'stop-color' found, use 'stopColor' instead  react/no-unknown-property
> 11:37:05.091 | 114:49  Error: Unknown property 'stop-opacity' found, use 'stopOpacity' instead  react/no-unknown-property
> ```

Ohh! Fixing it now

**Comment by jacksonh** [comment]
The dropdown selector shouldn't have this shadow on the main button, just on the dropdown when it opens.

Screen Shot 2022-03-23 at 21 59 53

**Comment by jacksonh** [comment]
The Download button for the browser extensions should redirect the user to the appropriate page. You can see the URLs in the old code:

```
const extensionDownloadLinks = {
  chrome: 'https://omnivore.app/install/chrome',
  safari: 'https://omnivore.app/install/mac',
  edge: 'https://omnivore.app/install/edge',
  firefox: 'https://omnivore.app/install/firefox',
}
```

**Comment by jacksonh** [comment]
The images (both preview images, and the Download on the AppStore) all look a little low resolution on my laptop. I think we need high definition versions of these exported from Figma also.

**Comment by jacksonh** [comment]
For both the `Learn more` underlined text they should be links to `/help/saving-links`

**Comment by jacksonh** [comment]
it looks like we need to break to the mobile design a little earlier or make this wide design more responsive

Screen Shot 2022-03-23 at 22 24 33

**Comment by jacksonh** [comment]
These should act as a toggle, where you can only select one option (default to the first selected).

It doesn't actually matter, since no matter what the user has selected we will redirect to `/install/apple` and the Apple App Store shows the appropriate app.

Screen Shot 2022-03-23 at 22 29 36

**Review by jacksonh — APPROVED** [review]

**Comment by jacksonh** [comment]
🚢

**Pull request merged**
