### PR TITLE
Text to Speech Reader Shortcut

### PR DESCRIPTION
**Pull request by satindar**

### CODE REVIEW

**Comment by satindar** [comment]
Need to fix the header colors and dismiss icon. I think modal is going to be the way to go here since nav view is going to be hard to wrestle into the mini player (if it would even work). 

There might also be a way to layer the mini player (in collapsed mode) back over the webview modal 🤔 

Simulator Screen Shot - iPhone 13 mini - 2022-08-30 at 15 02 17

**Comment by satindar** [comment]
@jacksonh Updated this to use NSNotification instead. Turned out to be pretty easy since we already had the viewModel setup for this.

**Comment by jacksonh** [comment]
Oh nice, going to try and test this out.

**Comment by jacksonh** [comment]
Notification thing is really cool. I changed this to make it tap on title, and then also added a menu item. That way advanced users can use the single tap, but there's still an easy to figure out version also.

**Comment by jacksonh** [comment]
Glad you figured out how to do this outside of a sheet.

**Pull request merged**
