### PR TITLE
return published date if the class name is omnivore-published-date which we added when we scraped the article

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Comment by sywhb** [comment]
Hey @jacksonh, I created a special `<div>` to contain the publication date of WeChat articles and handled it in Readability because we the current one we parsed does not have the correct timezone referring to #1837

**Comment by jacksonh** [comment]
Nice hack. Just wondering, would it be easier to return `create_date` if not null in `_checkPublishedDate` instead of inserting the div?

**Comment by sywhb** [comment]
@jacksonh because I'm not sure if the `create_time` could be accessed from Readability

**Review by jacksonh — APPROVED** [review]

**Comment by sywhb** [comment]
You mean using `<script>` tag to call the javascript?

**Pull request merged**
