### PR TITLE
feat: import opml handler

### PR DESCRIPTION
**Pull request by kimlimjustin**
Created OPML import handler, as discussed on #2870, by integrating https://github.com/danmactough/node-opmlparser solution into the `packages/import-handler` directory.

Yet, please note that due to insufficient up-to-date contributing docs and guidelines, this PR is made by literally reading the whole codebase manually, without actually running the application locally; this PR is only testified by running the mocha testing under the `import-handler` package. 

That being said, please try this PR and please let me know if any errors occurred or if any changes should be made further to complete this pull request,

Thank you and hope that the OPML handler can be part of omnivore soon shortly!

### CODE REVIEW

**Comment by kallekn** [comment]
This is a deal breaker. Omnivore looks nice, but I need to be able to import my feeds in order to use it.

**Comment by natarslan** [comment]
Following this! Would be great to bulk import feeds (opml).

**Comment by cori** [comment]
> I don't think our handling of lots of RSS feeds is great yet

What's the internal perception of "lots" here? My OPML file has ~5 dozen feeds. Is that a lot in this context?

**Comment by axgdcode** [comment]
> Hey this is an interesting way of doing it. We actually do have an OPML API also but we haven't exposed it on the web, just because I don't think our handling of lots of RSS feeds is great yet.
In anticipation of the self-hosted mode, I believe this feature should be enabled exclusively for that mode.

**Comment by jacksonh** [comment]
> > Hey this is an interesting way of doing it. We actually do have an OPML API also but we haven't exposed it on the web, just because I don't think our handling of lots of RSS feeds is great yet.
> 
> In anticipation of the self-hosted mode, I believe this feature should be enabled exclusively for that mode. @jacksonh

HI, yes you could call this API on your self hosted version now. Just use the `scanFeeds` API.

**Pull request closed without merging**
