### PR TITLE
drop original_content column from library_item table

### PR DESCRIPTION
**Pull request by sywhb**

### CODE REVIEW

**Comment by jacksonh** [comment]
Is it possible to do `IF EXISTS` with `DROP`?

**Comment by sywhb** [comment]
> Is it possible to do `IF EXISTS` with `DROP`?

I don't think it is supported

**Comment by sywhb** [comment]
`@jacksonh I guess I was wrong: `DROP [ COLUMN ] [ IF EXISTS ] column_name [ RESTRICT | CASCADE ]`
https://www.postgresql.org/docs/12/sql-altertable.html

**Comment by sywhb** [comment]
@jacksonh Added `IF EXISTS` to the migration sql

**Review by jacksonh — APPROVED** [review]

**Pull request merged**
